name: snapone # you probably want to 'snapcraft register <name>'
base: core20 # the base snap is the execution environment for this snap
version: '0.1' # just for humans, typically '1.2+git' or '1.3.2'
summary: Single-line elevator pitch for your amazing snap # 79 char long summary
description: |
  This is my-snap's description. You have a paragraph or two to tell the
  most important story about your snap. Keep it under 100 words though,
  we live in tweetspace and your description wants to look good in the snap
  store.

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: classic # use 'strict' once you have the right plugs and slots

apps:
  apache:
    command: apache2ctl start
    daemon: simple
    restart-condition: always
    plugs: [network, network-bind, removable-media]

parts:
  apache:
    source: .
    plugin: python	#Ho scelto python perché nella stessa "part" dopo ci sarà l'app django
    override-prime: |
     apt-get update
     apt install apache2 -y
     cp /root/project/envvars /etc/apache2/envvars
     cp /root/project/apache2.conf /etc/apache2/apache2.conf
     cp /root/project/apache2ctl /usr/sbin/apache2ctl
     cp /usr/sbin/apache2ctl /root/prime
#Lo script di sopra esegue i seguenti comandi:
#1) Installa apache2
#2) Copia le variabili d'ambiente provviste di ${SNAÞ} al posto del file predefinito da apache
#3) Copia la configurazione di apache anch'essa provvista di variabili d'ambiente
#4) Sostituisce anche nello script apache2ctl le opportune variabili (il problema è generato da questo script)
#5) Mette lo script apache2ctl nella dir "prime" che poi sarà visibile anche all'esterno dell'ambiente virtuale permettendone l'esecuzione.
